#!/bin/bash

# Remover arquivo se existir
rm -f ~/x

echo "Instalando termux-am"
pkg install termux-am -y 

# Configurar armazenamento
termux-setup-storage & sleep 4 

# Aguardar permissão de armazenamento
while [ ! -d ~/storage/shared ]; do
    echo "Permissão de armazenamento negada. Aguardando..."
    sleep 3
done

# Instalar pacotes do Termux
echo "Instalando pacotes do Termux"
apt-get update -y
apt-get -y --with-new-pkgs -o Dpkg::Options::="--force-confdef" upgrade >/dev/null 2>&1
pkg install x11-repo pulseaudio xwayland wget tsu root-repo patchelf p7zip xorg-xrandr ncurses-utils hashdeep termux-x11-nightly -y &>/dev/null

# Remover glibc anterior, se existir
if [ -e "$PREFIX/glibc" ]; then
    read -p "Excluir glibc anterior. Continuar? (Y/n): " answer
    if [ "$answer" = "Y" ] || [ "$answer" = "y" ]; then
        rm -rf "$PREFIX/glibc"
    else
        exit 1
    fi
fi

# Selecionar opção de instalação
echo "Selecione uma opção"
echo "1) Instalar versão mobox anterior com box86"
echo "2) Instalar nova versão mobox wow64"
read -p "Número selecionado: " option

# Instalar mobox
echo "Instalando mobox"
case "$option" in
    1)
        INSTALL_WOW64=0
        ;;
    2)
        INSTALL_WOW64=1
        ;;
    *)
        echo "Opção inválida."
        exit 1
        ;;
esac

# Função para baixar arquivos do GitLab
function wget-git-q {
    wget -q --retry-connrefused --tries=0 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/repository/files/$1/raw?ref=main" -O "$2"
    return $?
}

# Atualizar gerenciador de pacotes
echo "Atualizando gerenciador de pacotes"
mkdir -p "$PREFIX/glibc/opt/package-manager/installed"

if [ "$INSTALL_WOW64" = "1" ]; then
    PRIVATE_TOKEN="glpat-h5r7HjKoPKZPxmfg79xs"
    PROJECT_ID=54240888
else
    PRIVATE_TOKEN="glpat-Xs4HfrCkMpbedkPycqzP"
    PROJECT_ID=52465323
fi

if ! wget-git-q "package-manager" "$PREFIX/glibc/opt/package-manager/package-manager"; then
    echo "Falha ao baixar."
    exit 1
fi

. "$PREFIX/glibc/opt/package-manager/token"
sync-all

if [ "$INSTALL_WOW64" = "1" ]; then
    sync-package wine-9.3-vanilla-wow64
else
    sync-package wine-ge-custom-8-25
fi

ln -sf "$PREFIX/glibc/opt/scripts/mobox" "$PREFIX/bin/mobox"
echo "Para iniciar, digite \"mobox\""
